// <auto-generated />
namespace Pack4Travel.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixReference : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixReference));
        
        string IMigrationMetadata.Id
        {
            get { return "201707291757472_FixReference"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
